## stocc random project @anchor supplement_acknowledgements_code_reuse_stocc

The implementation of the hypergeometric distribution functions
@link genesis::utils::multivariate_hypergeometric_distribution() multivariate_hypergeometric_distribution()@endlink,
@link genesis::utils::hypergeometric_distribution() hypergeometric_distribution()@endlink,
@link genesis::utils::hypergeometric_distribution_inversion_mode_() hypergeometric_distribution_inversion_mode_()@endlink,
@link genesis::utils::hypergeometric_distribution_ratio_of_unifoms_() hypergeometric_distribution_ratio_of_unifoms_()@endlink,
are based on the stocc.zip non-uniform random number generator functions by Agner Fog.
The original code is published under the GNU General Public Licence.

> Author:        Agner Fog
> Date created:  2002-01-04
> Last modified: 2008-11-30
> Project:       stocc.zip
> Source URL:    www.agner.org/random
>
> Description:
> Non-uniform random number generator functions.
>
> This file contains source code for the class StochasticLib1 defined in stocc.h.
>
> Documentation:
> ==============
> The file stocc.h contains class definitions.
> The file stocc.htm contains further instructions.
> The file distrib.pdf contains definitions of the statistic distributions.
> The file sampmet.pdf contains theoretical descriptions of the methods used
> for sampling from these distributions.
> The file ran-instructions.pdf contains general instructions.
>
> Copyright 2002-2008 by Agner Fog.
> GNU General Public License http://www.gnu.org/licenses/gpl.html

As we use the same license, see @ref supplement_license for the complete license.
