## MinEncCanKmer @anchor supplement_acknowledgements_code_reuse_min_enc_can_kmer

The implementation of the minimal encoding of canonical k-mers in
@link genesis::sequence::MinimalCanonicalEncoding MinimalCanonicalEncoding@endlink
is based on the implementation at https://gitlab.ub.uni-bielefeld.de/gi/MinEncCanKmer
which is published under the GNU General Public License v3.0 or later,
with copyright (C) 2022-2023 Roland Wittler <roland.wittler@uni-bielefeld.de>.

The concept is described in the following excellent manuscript:

> Wittler, Roland. 2023. “General Encoding of Canonical k-Mers.” Peer Community Journal 3 (e87).
> https://doi.org/10.24072/pcjournal.323.

See there and the original code repository for details.
As we use the same license, see @ref supplement_license for the complete license.
