## MD5 @anchor supplement_acknowledgements_code_reuse_md

Our implementation of the @link genesis::utils::MD5 MD5 hashing function@endlink is based on
http://www.zedwood.com/article/cpp-md5-function,
which itself was converted to C++ class by Frank Thilo (thilo@unix-ag.org) for bzflag
(http://www.bzflag.org), and is based on the reference implementation of `RFC 1321`:

@htmlonly <details><summary>License</summary> @endhtmlonly
>    Copyright (C) 1991-2, RSA Data Security, Inc. Created 1991. All rights reserved.
>
>    License to copy and use this software is granted provided that it
>    is identified as the "RSA Data Security, Inc. MD5 Message-Digest
>    Algorithm" in all material mentioning or referencing this software
>    or this function.
>
>    License is also granted to make and use derivative works provided
>    that such works are identified as "derived from the RSA Data
>    Security, Inc. MD5 Message-Digest Algorithm" in all material
>    mentioning or referencing the derived work.
>
>    RSA Data Security, Inc. makes no representations concerning either
>    the merchantability of this software or the suitability of this
>    software for any particular purpose. It is provided "as is"
>    without express or implied warranty of any kind.
>
>    These notices must be retained in any copies of any part of this
>    documentation and/or software.
@htmlonly </details> @endhtmlonly
