#ifndef GENESIS_H_
#define GENESIS_H_

/*
    Genesis - A toolkit for working with phylogenetic data.
    Copyright (C) 2014-2017 Lucas Czech

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Contact:
    Lucas Czech <lucas.czech@h-its.org>
    Exelixis Lab, Heidelberg Institute for Theoretical Studies
    Schloss-Wolfsbrunnenweg 35, D-69118 Heidelberg, Germany
*/

/**
 * @brief This header includes all other genesis headers (*.hpp).
 * This makes it easy to integrate the code as a library, as all
 * symbols of genesis are available after including this header.
 *
 * You do not need to edit this file manually. Simply run the script
 * make_genesis_header.sh in ./tools to update this file.
 */

#include "genesis/placement/formats/edge_color.hpp"
#include "genesis/placement/formats/jplace_reader.hpp"
#include "genesis/placement/formats/jplace_writer.hpp"
#include "genesis/placement/formats/newick_reader.hpp"
#include "genesis/placement/formats/newick_writer.hpp"
#include "genesis/placement/formats/serializer.hpp"
#include "genesis/placement/function/epca.hpp"
#include "genesis/placement/function/functions.hpp"
#include "genesis/placement/function/helper.hpp"
#include "genesis/placement/function/measures.hpp"
#include "genesis/placement/function/operators.hpp"
#include "genesis/placement/function/sample_set.hpp"
#include "genesis/placement/function/tree.hpp"
#include "genesis/placement/placement_tree.hpp"
#include "genesis/placement/pquery/distances.hpp"
#include "genesis/placement/pquery.hpp"
#include "genesis/placement/pquery/name.hpp"
#include "genesis/placement/pquery/placement.hpp"
#include "genesis/placement/pquery/plain.hpp"
#include "genesis/placement/sample.hpp"
#include "genesis/placement/sample_set.hpp"
#include "genesis/placement/simulator/distributions.hpp"
#include "genesis/placement/simulator/functions.hpp"
#include "genesis/placement/simulator/simulator.hpp"

#include "genesis/sequence/counts.hpp"
#include "genesis/sequence/formats/fasta_input_iterator.hpp"
#include "genesis/sequence/formats/fasta_output_iterator.hpp"
#include "genesis/sequence/formats/fasta_reader.hpp"
#include "genesis/sequence/formats/fasta_writer.hpp"
#include "genesis/sequence/formats/phylip_reader.hpp"
#include "genesis/sequence/formats/phylip_writer.hpp"
#include "genesis/sequence/functions/codes.hpp"
#include "genesis/sequence/functions/consensus.hpp"
#include "genesis/sequence/functions/entropy.hpp"
#include "genesis/sequence/functions/functions.hpp"
#include "genesis/sequence/functions/labels.hpp"
#include "genesis/sequence/functions/stats.hpp"
#include "genesis/sequence/printers/bitmap.hpp"
#include "genesis/sequence/printers/simple.hpp"
#include "genesis/sequence/sequence.hpp"
#include "genesis/sequence/sequence_set.hpp"

#include "genesis/taxonomy/formats/taxonomy_reader.hpp"
#include "genesis/taxonomy/formats/taxopath_generator.hpp"
#include "genesis/taxonomy/formats/taxopath_parser.hpp"
#include "genesis/taxonomy/functions/entropy_data.hpp"
#include "genesis/taxonomy/functions/entropy.hpp"
#include "genesis/taxonomy/functions/operators.hpp"
#include "genesis/taxonomy/functions/ranks.hpp"
#include "genesis/taxonomy/functions/taxonomy.hpp"
#include "genesis/taxonomy/functions/taxopath.hpp"
#include "genesis/taxonomy/iterator/levelorder.hpp"
#include "genesis/taxonomy/iterator/postorder.hpp"
#include "genesis/taxonomy/iterator/preorder.hpp"
#include "genesis/taxonomy/printers/nested.hpp"
#include "genesis/taxonomy/taxon_data.hpp"
#include "genesis/taxonomy/taxon.hpp"
#include "genesis/taxonomy/taxonomy.hpp"
#include "genesis/taxonomy/taxopath.hpp"

#include "genesis/tree/attribute_tree/indexed_newick_reader.hpp"
#include "genesis/tree/attribute_tree/keyed_newick_reader.hpp"
#include "genesis/tree/attribute_tree/tree.hpp"
#include "genesis/tree/bipartition/bipartition.hpp"
#include "genesis/tree/bipartition/bipartition_set.hpp"
#include "genesis/tree/default/distances.hpp"
#include "genesis/tree/default/edge_color.hpp"
#include "genesis/tree/default/functions.hpp"
#include "genesis/tree/default/newick_reader.hpp"
#include "genesis/tree/default/newick_writer.hpp"
#include "genesis/tree/default/operators.hpp"
#include "genesis/tree/default/phyloxml_writer.hpp"
#include "genesis/tree/default/tree.hpp"
#include "genesis/tree/drawing/circular_layout.hpp"
#include "genesis/tree/drawing/circular_tree.hpp"
#include "genesis/tree/drawing/layout_tree.hpp"
#include "genesis/tree/drawing/rectangular_layout.hpp"
#include "genesis/tree/drawing/rectangular_tree.hpp"
#include "genesis/tree/formats/color_writer_plugin.hpp"
#include "genesis/tree/formats/newick/broker.hpp"
#include "genesis/tree/formats/newick/color_writer_plugin.hpp"
#include "genesis/tree/formats/newick/element.hpp"
#include "genesis/tree/formats/newick/input_iterator.hpp"
#include "genesis/tree/formats/newick/reader.hpp"
#include "genesis/tree/formats/newick/writer.hpp"
#include "genesis/tree/formats/phyloxml/color_writer_plugin.hpp"
#include "genesis/tree/formats/phyloxml/writer.hpp"
#include "genesis/tree/function/distances.hpp"
#include "genesis/tree/function/functions.hpp"
#include "genesis/tree/function/manipulation.hpp"
#include "genesis/tree/function/operators.hpp"
#include "genesis/tree/function/tree_set.hpp"
#include "genesis/tree/iterator/eulertour.hpp"
#include "genesis/tree/iterator/inorder.hpp"
#include "genesis/tree/iterator/levelorder.hpp"
#include "genesis/tree/iterator/node_links.hpp"
#include "genesis/tree/iterator/path.hpp"
#include "genesis/tree/iterator/path_set.hpp"
#include "genesis/tree/iterator/postorder.hpp"
#include "genesis/tree/iterator/preorder.hpp"
#include "genesis/tree/mass_tree/functions.hpp"
#include "genesis/tree/mass_tree/kmeans.hpp"
#include "genesis/tree/mass_tree/tree.hpp"
#include "genesis/tree/printer/compact.hpp"
#include "genesis/tree/printer/detailed.hpp"
#include "genesis/tree/printer/table.hpp"
#include "genesis/tree/tree/edge_data.hpp"
#include "genesis/tree/tree/edge.hpp"
#include "genesis/tree/tree.hpp"
#include "genesis/tree/tree/link.hpp"
#include "genesis/tree/tree/node_data.hpp"
#include "genesis/tree/tree/node.hpp"
#include "genesis/tree/tree_set.hpp"

#include "genesis/utils/containers/sorted_vector.hpp"
#include "genesis/utils/containers/sorted_vector/operators.hpp"
#include "genesis/utils/core/algorithm.hpp"
#include "genesis/utils/core/fs.hpp"
#include "genesis/utils/core/indexed_list.hpp"
#include "genesis/utils/core/logging.hpp"
#include "genesis/utils/core/options.hpp"
#include "genesis/utils/core/range.hpp"
#include "genesis/utils/core/std.hpp"
#include "genesis/utils/core/version.hpp"
#include "genesis/utils/formats/bmp/writer.hpp"
#include "genesis/utils/formats/csv/reader.hpp"
#include "genesis/utils/formats/json/document.hpp"
#include "genesis/utils/formats/json/iterator.hpp"
#include "genesis/utils/formats/json/reader.hpp"
#include "genesis/utils/formats/json/writer.hpp"
#include "genesis/utils/formats/nexus/block.hpp"
#include "genesis/utils/formats/nexus/document.hpp"
#include "genesis/utils/formats/nexus/taxa.hpp"
#include "genesis/utils/formats/nexus/trees.hpp"
#include "genesis/utils/formats/nexus/writer.hpp"
#include "genesis/utils/formats/svg/attributes.hpp"
#include "genesis/utils/formats/svg/definitions.hpp"
#include "genesis/utils/formats/svg/document.hpp"
#include "genesis/utils/formats/svg/gradient.hpp"
#include "genesis/utils/formats/svg/group.hpp"
#include "genesis/utils/formats/svg/helper.hpp"
#include "genesis/utils/formats/svg/object.hpp"
#include "genesis/utils/formats/svg/shapes.hpp"
#include "genesis/utils/formats/svg/svg.hpp"
#include "genesis/utils/formats/svg/text.hpp"
#include "genesis/utils/formats/xml/document.hpp"
#include "genesis/utils/formats/xml/helper.hpp"
#include "genesis/utils/formats/xml/writer.hpp"
#include "genesis/utils/io/input_reader.hpp"
#include "genesis/utils/io/input_source.hpp"
#include "genesis/utils/io/input_stream.hpp"
#include "genesis/utils/io/output_stream.hpp"
#include "genesis/utils/io/parser.hpp"
#include "genesis/utils/io/scanner.hpp"
#include "genesis/utils/io/serializer.hpp"
#include "genesis/utils/math/bitvector.hpp"
#include "genesis/utils/math/common.hpp"
#include "genesis/utils/math/histogram/accumulator.hpp"
#include "genesis/utils/math/histogram/distances.hpp"
#include "genesis/utils/math/histogram.hpp"
#include "genesis/utils/math/histogram/operations.hpp"
#include "genesis/utils/math/histogram/operators.hpp"
#include "genesis/utils/math/histogram/stats.hpp"
#include "genesis/utils/math/kmeans.hpp"
#include "genesis/utils/math/matrix.hpp"
#include "genesis/utils/math/matrix/operators.hpp"
#include "genesis/utils/math/matrix/pca.hpp"
#include "genesis/utils/math/matrix/statistics.hpp"
#include "genesis/utils/math/random.hpp"
#include "genesis/utils/math/range_minimum_query.hpp"
#include "genesis/utils/math/sha1.hpp"
#include "genesis/utils/math/twobit_vector/functions.hpp"
#include "genesis/utils/math/twobit_vector.hpp"
#include "genesis/utils/math/twobit_vector/iterator_deletions.hpp"
#include "genesis/utils/math/twobit_vector/iterator_insertions.hpp"
#include "genesis/utils/math/twobit_vector/iterator_substitutions.hpp"
#include "genesis/utils/text/char.hpp"
#include "genesis/utils/text/string.hpp"
#include "genesis/utils/text/style.hpp"
#include "genesis/utils/text/table.hpp"
#include "genesis/utils/tools/char_lookup.hpp"
#include "genesis/utils/tools/color/gradient.hpp"
#include "genesis/utils/tools/color.hpp"
#include "genesis/utils/tools/color/names.hpp"
#include "genesis/utils/tools/color/operators.hpp"
#include "genesis/utils/tools/color/palettes.hpp"
#include "genesis/utils/tools/date_time.hpp"
#include "genesis/utils/tools/tickmarks.hpp"

#endif // include guard
